<?php

$labels = [];

$labels['quota_plugin_title'] = 'Квота на пощенската кутия';
$labels['chart_title'] = 'Използвано пространство';
$labels['space_used'] = 'Използвано пространство';
$labels['space_free'] = 'Свободно пространство';
$labels['quota_meet_90'] = 'Вие използвате над 90% от вашата квота за дисково пространство.';
$labels['quota_meet_99'] = 'Вие използвате над 99% от вашата квота за дисково пространство.';
$labels['problem_please_contact'] = 'Въпроси и коментари на: %s.';
$labels['unknown'] = 'Няма данни.';
