<?php
$labels = array();
$labels['quota_plugin_title'] = 'Mailbox Quota';
$labels['space_used'] = 'Space used: ';
$labels['space_free'] = 'Space free: ';
$labels['quota_meet_90'] = 'You have used over 90% of your storage quota.';
$labels['quota_meet_99'] = 'You have used over 99% of your storage quota.';
$labels['problem_please_contact'] = 'If you have any question, please contact <a href="mailto:opr@ee.nthu.edu.tw">opr@ee.nthu.edu.tw</a>.';
$labels['unknown'] = 'unknown';
