<?php

$labels = [];

$labels['quota_plugin_title'] = 'Mailkonto kvote';
$labels['chart_title'] = 'Forbruksoversikt';
$labels['space_used'] = 'Brukt';
$labels['space_free'] = 'Ledig';
$labels['quota_meet_90'] = 'Du har brukt over 90% av din lagringskvote.';
$labels['quota_meet_99'] = 'Du har brukt over 99% av din lagringskvote.';
$labels['problem_please_contact'] = 'Hvis du har spørmål om kvoter, kontakt %s.';
$labels['unknown'] = 'ukjent';
