<?php

$labels = [];

$labels['quota_plugin_title'] = 'Limit skrzynki pocztowej';
$labels['chart_title'] = 'Wykres zajętości miejsca';
$labels['space_used'] = 'Przestrzeń używana';
$labels['space_free'] = 'Przestrzeń wolna';
$labels['quota_meet_90'] = 'Aktualnie używasz ponad 90% wielkości skrzynki.';
$labels['quota_meet_99'] = 'Aktualnie używasz ponad 99% wielkości skrzynki.';
$labels['problem_please_contact'] = 'W razie pytań lub problemów zapraszamy do kontaktu pod adresem %s.';
$labels['unknown'] = 'brak danych';
