<?php

// Por Marcelo Leães - marcelo@eth1.com.br

$labels = [];

$labels['quota_plugin_title'] = 'Quota';
$labels['chart_title'] = 'Gráfico de Utilização';
$labels['space_used'] = 'Utilizado';
$labels['space_free'] = 'Livre';
$labels['quota_meet_90'] = 'Sua caixa alcançou 90% do espaço disponível.';
$labels['quota_meet_99'] = 'Sua caixa alcançou 99% do espaço disponível.';
$labels['problem_please_contact'] = '<br/>Para solicitar ajuste no tamanho de sua caixa contate: %s';
$labels['unknown'] = 'desconhecido';
