<?php

$labels = [];

$labels['quota_plugin_title'] = 'Poraba prostora';
$labels['chart_title'] = 'Graf prostora';
$labels['space_used'] = 'Uporabljen prostor';
$labels['space_free'] = 'Prostor na voljo';
$labels['quota_meet_90'] = 'Porabili ste preko 90% vašega dodeljenega prostora.';
$labels['quota_meet_99'] = 'Porabili ste preko 99% vašega dodeljenega prostora.';
$labels['problem_please_contact'] = 'V primeru vprašanj, prosimo, kontaktirajte %s.';
$labels['unknown'] = 'neznano';
